class Country {
  String code;
  String name;

  Country({required this.code, required this.name});
}

List<Country> getCountries() {
  return [
    Country(code: "AF", name: "Afghanistan"),
    Country(code: "AX", name: "Åland Islands"),
    Country(code: "AL", name: "Albania"),
    Country(code: "DZ", name: "Algeria"),
    Country(code: "AS", name: "American Samoa"),
    Country(code: "AD", name: "Andorra"),
    Country(code: "AO", name: "Angola"),
    Country(code: "AI", name: "Anguilla"),
    Country(code: "AQ", name: "Antarctica"),
    Country(code: "AG", name: "Antigua and Barbuda"),
    Country(code: "AR", name: "Argentina"),
    Country(code: "AM", name: "Armenia"),
    Country(code: "AW", name: "Aruba"),
    Country(code: "AU", name: "Australia"),
    Country(code: "AT", name: "Austria"),
    Country(code: "AZ", name: "Azerbaijan"),
    Country(code: "BS", name: "Bahamas"),
    Country(code: "BH", name: "Bahrain"),
    Country(code: "BD", name: "Bangladesh"),
    Country(code: "BB", name: "Barbados"),
    Country(code: "BY", name: "Belarus"),
    Country(code: "BE", name: "Belgium"),
    Country(code: "BZ", name: "Belize"),
    Country(code: "BJ", name: "Benin"),
    Country(code: "BM", name: "Bermuda"),
    Country(code: "BT", name: "Bhutan"),
    Country(code: "BO", name: "Bolivia"),
    Country(code: "BQ", name: "Bonaire"),
    Country(code: "BA", name: "Bosnia and Herzegovina"),
    Country(code: "BW", name: "Botswana"),
    Country(code: "BV", name: "Bouvet Island"),
    Country(code: "BR", name: "Brazil"),
    Country(code: "IO", name: "British Indian Ocean Territory"),
    Country(code: "VG", name: "British Virgin Islands"),
    Country(code: "BN", name: "Brunei Darussalam"),
    Country(code: "BG", name: "Bulgaria"),
    Country(code: "BF", name: "Burkina Faso"),
    Country(code: "BI", name: "Burundi"),
    Country(code: "CV", name: "Cabo Verde"),
    Country(code: "KH", name: "Cambodia"),
    Country(code: "CM", name: "Cameroon"),
    Country(code: "CA", name: "Canada"),
    Country(code: "KY", name: "Cayman Islands"),
    Country(code: "CF", name: "Central African Republic"),
    Country(code: "TD", name: "Chad"),
    Country(code: "CL", name: "Chile"),
    Country(code: "CN", name: "China"),
    Country(code: "CX", name: "Christmas Island"),
    Country(code: "CC", name: "Cocos Islands"),
    Country(code: "CO", name: "Colombia"),
    Country(code: "KM", name: "Comoros"),
    Country(code: "CG", name: "Congo"),
    Country(code: "CD", name: "Congo Democratic Republic Of"),
    Country(code: "CK", name: "Cook Islands"),
    Country(code: "CR", name: "Costa Rica"),
    Country(code: "CI", name: "Cote D'ivoire"),
    Country(code: "HR", name: "Croatia"),
    Country(code: "CU", name: "Cuba"),
    Country(code: "CW", name: "Curacao"),
    Country(code: "CY", name: "Cyprus"),
    Country(code: "CZ", name: "Czechia"),
    Country(code: "DK", name: "Denmark"),
    Country(code: "DJ", name: "Djibouti"),
    Country(code: "DM", name: "Dominica"),
    Country(code: "DO", name: "Dominican Republic"),
    Country(code: "EC", name: "Ecuador"),
    Country(code: "EG", name: "Egypt"),
    Country(code: "SV", name: "El Salvador"),
    Country(code: "GQ", name: "Equatorial Guinea"),
    Country(code: "ER", name: "Eritrea"),
    Country(code: "EE", name: "Estonia"),
    Country(code: "ET", name: "Ethiopia"),
    Country(code: "FK", name: "Falkland Islands"),
    Country(code: "FO", name: "Faroe Islands"),
    Country(code: "FJ", name: "Fiji"),
    Country(code: "FI", name: "Finland"),
    Country(code: "FR", name: "France"),
    Country(code: "GF", name: "French Guiana"),
    Country(code: "PF", name: "French Polynesia"),
    Country(code: "TF", name: "French Southern Territories"),
    Country(code: "GA", name: "Gabon"),
    Country(code: "GM", name: "Gambia"),
    Country(code: "GE", name: "Georgia"),
    Country(code: "DE", name: "Germany"),
    Country(code: "GH", name: "Ghana"),
    Country(code: "GI", name: "Gibraltar"),
    Country(code: "GR", name: "Greece"),
    Country(code: "GL", name: "Greenland"),
    Country(code: "GD", name: "Grenada"),
    Country(code: "GP", name: "Guadeloupe"),
    Country(code: "GU", name: "Guam"),
    Country(code: "GT", name: "Guatemala"),
    Country(code: "GG", name: "Guernsey"),
    Country(code: "GN", name: "Guinea"),
    Country(code: "GW", name: "Guinea Bissau"),
    Country(code: "GY", name: "Guyana"),
    Country(code: "HT", name: "Haiti"),
    Country(code: "HM", name: "Heard Island and McDonald Islands"),
    Country(code: "HN", name: "Honduras"),
    Country(code: "HK", name: "Hong Kong"),
    Country(code: "HU", name: "Hungary"),
    Country(code: "IS", name: "Iceland"),
    Country(code: "IN", name: "India"),
    Country(code: "ID", name: "Indonesia"),
    Country(code: "IR", name: "Iran"),
    Country(code: "IQ", name: "Iraq"),
    Country(code: "IE", name: "Ireland"),
    Country(code: "IM", name: "Isle of Man"),
    Country(code: "IL", name: "Israel"),
    Country(code: "IT", name: "Italy"),
    Country(code: "JM", name: "Jamaica"),
    Country(code: "JP", name: "Japan"),
    Country(code: "JE", name: "Jersey"),
    Country(code: "JO", name: "Jordan"),
    Country(code: "KZ", name: "Kazakhstan"),
    Country(code: "KE", name: "Kenya"),
    Country(code: "KI", name: "Kiribati"),
    Country(code: "KW", name: "Kuwait"),
    Country(code: "KG", name: "Kyrgyzstan"),
    Country(code: "LA", name: "Laos"),
    Country(code: "LV", name: "Latvia"),
    Country(code: "LB", name: "Lebanon"),
    Country(code: "LS", name: "Lesotho"),
    Country(code: "LR", name: "Liberia"),
    Country(code: "LY", name: "Libya"),
    Country(code: "LI", name: "Liechtenstein"),
    Country(code: "LT", name: "Lithuania"),
    Country(code: "LU", name: "Luxembourg"),
    Country(code: "MO", name: "Macao"),
    Country(code: "MK", name: "Macedonia"),
    Country(code: "MG", name: "Madagascar"),
    Country(code: "MW", name: "Malawi"),
    Country(code: "MY", name: "Malaysia"),
    Country(code: "MV", name: "Maldives"),
    Country(code: "ML", name: "Mali"),
    Country(code: "MT", name: "Malta"),
    Country(code: "MH", name: "Marshall Islands"),
    Country(code: "MQ", name: "Martinique"),
    Country(code: "MR", name: "Mauritania"),
    Country(code: "MU", name: "Mauritius"),
    Country(code: "YT", name: "Mayotte"),
    Country(code: "MX", name: "Mexico"),
    Country(code: "FM", name: "Micronesia"),
    Country(code: "MD", name: "Moldova"),
    Country(code: "MC", name: "Monaco"),
    Country(code: "MN", name: "Mongolia"),
    Country(code: "ME", name: "Montenegro"),
    Country(code: "MS", name: "Montserrat"),
    Country(code: "MA", name: "Morocco"),
    Country(code: "MZ", name: "Mozambique"),
    Country(code: "MM", name: "Myanmar"),
    Country(code: "NA", name: "Namibia"),
    Country(code: "NR", name: "Nauru"),
    Country(code: "NP", name: "Nepal"),
    Country(code: "NL", name: "Netherlands"),
    Country(code: "NC", name: "New Caledonia"),
    Country(code: "NZ", name: "New Zealand"),
    Country(code: "NI", name: "Nicaragua"),
    Country(code: "NE", name: "Niger"),
    Country(code: "NG", name: "Nigeria"),
    Country(code: "NU", name: "Niue"),
    Country(code: "NF", name: "Norfolk Island"),
    Country(code: "KP", name: "North Korea"),
    Country(code: "MP", name: "Northern Mariana Islands"),
    Country(code: "NO", name: "Norway"),
    Country(code: "OM", name: "Oman"),
    Country(code: "PK", name: "Pakistan"),
    Country(code: "PW", name: "Palau"),
    Country(code: "PS", name: "Palestine"),
    Country(code: "PA", name: "Panama"),
    Country(code: "PG", name: "Papua New Guinea"),
    Country(code: "PY", name: "Paraguay"),
    Country(code: "PE", name: "Peru"),
    Country(code: "PH", name: "Philippines"),
    Country(code: "PN", name: "Pitcairn"),
    Country(code: "PL", name: "Poland"),
    Country(code: "PT", name: "Portugal"),
    Country(code: "PR", name: "Puerto Rico"),
    Country(code: "QA", name: "Qatar"),
    Country(code: "RE", name: "Reunion"),
    Country(code: "RO", name: "Romania"),
    Country(code: "RU", name: "Russian Federation"),
    Country(code: "RW", name: "Rwanda"),
    Country(code: "BL", name: "Saint Barthelemy"),
    Country(code: "SH", name: "Saint Helena"),
    Country(code: "KN", name: "Saint Kitts and Nevis"),
    Country(code: "LC", name: "Saint Lucia"),
    Country(code: "MF", name: "Saint Martin"),
    Country(code: "PM", name: "Saint Pierre and Miquelon"),
    Country(code: "VC", name: "Saint Vincent and The Grenadines"),
    Country(code: "WS", name: "Samoa"),
    Country(code: "SM", name: "San Marino"),
    Country(code: "ST", name: "Sao Tome and Principe"),
    Country(code: "SA", name: "Saudi Arabia"),
    Country(code: "SN", name: "Senegal"),
    Country(code: "RS", name: "Serbia"),
    Country(code: "SC", name: "Seychelles"),
    Country(code: "SL", name: "Sierra Leone"),
    Country(code: "SG", name: "Singapore"),
    Country(code: "SX", name: "Sint Maarten"),
    Country(code: "SK", name: "Slovakia"),
    Country(code: "SI", name: "Slovenia"),
    Country(code: "SB", name: "Solomon Islands"),
    Country(code: "SO", name: "Somalia"),
    Country(code: "ZA", name: "South Africa"),
    Country(code: "GS", name: "South Georgia and The South Sandwich Islands"),
    Country(code: "KR", name: "South Korea"),
    Country(code: "SS", name: "South Sudan"),
    Country(code: "ES", name: "Spain"),
    Country(code: "LK", name: "Sri Lanka"),
    Country(code: "SD", name: "Sudan"),
    Country(code: "SR", name: "Suriname"),
    Country(code: "SJ", name: "Svalbard and Jan Mayen"),
    Country(code: "SZ", name: "Swaziland"),
    Country(code: "SE", name: "Sweden"),
    Country(code: "CH", name: "Switzerland"),
    Country(code: "SY", name: "Syrian Arab Republic"),
    Country(code: "TW", name: "Taiwan"),
    Country(code: "TJ", name: "Tajikistan"),
    Country(code: "TZ", name: "Tanzania"),
    Country(code: "TH", name: "Thailand"),
    Country(code: "TL", name: "Timor Leste"),
    Country(code: "TG", name: "Togo"),
    Country(code: "TK", name: "Tokelau"),
    Country(code: "TO", name: "Tonga"),
    Country(code: "TT", name: "Trinidad and Tobago"),
    Country(code: "TN", name: "Tunisia"),
    Country(code: "TR", name: "Turkey"),
    Country(code: "TM", name: "Turkmenistan"),
    Country(code: "TC", name: "Turks and Caicos Islands"),
    Country(code: "TV", name: "Tuvalu"),
    Country(code: "UG", name: "Uganda"),
    Country(code: "UA", name: "Ukraine"),
    Country(code: "AE", name: "United Arab Emirates"),
    Country(code: "GB", name: "United Kingdom"),
    Country(code: "US", name: "United States"),
    Country(code: "UM", name: "United States minor outlying islands"),
    Country(code: "UY", name: "Uruguay"),
    Country(code: "VI", name: "US Virgin Islands"),
    Country(code: "UZ", name: "Uzbekistan"),
    Country(code: "VU", name: "Vanuatu"),
    Country(code: "VA", name: "Vatican City"),
    Country(code: "VE", name: "Venezuela"),
    Country(code: "VN", name: "Viet Nam"),
    Country(code: "WF", name: "Wallis and Futuna"),
    Country(code: "EH", name: "Western Sahara"),
    Country(code: "YE", name: "Yemen"),
    Country(code: "ZM", name: "Zambia"),
    Country(code: "ZW", name: "Zimbabwe"),
  ];
}
