name: poddr
description: A multiplatform podcast player built in Flutter.

publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^5.0.5
  universal_platform: ^1.0.0+1
  firebase_core: ^1.18.0
  firebase_auth: ^3.4.1
  firebase_core_desktop: ^1.0.0
  firebase_auth_desktop: ^1.0.0
  flutter_riverpod: ^2.0.2
  http: ^0.13.4
  podcast_search: ^0.5.1
  just_audio: ^0.9.28
  just_audio_background: ^0.0.1-beta.7
  just_audio_windows: ^0.1.0
  just_audio_mpv: ^0.1.5
  audio_session: ^0.1.10
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.5

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface : 4.5.1
  #dio: "4.0.4"
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
  