// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQ6hHinNo2xBvgfxO6UVmX3wEndSFim8',
    appId: '1:77230078110:web:8e601a2183b2959f6e238f',
    messagingSenderId: '77230078110',
    projectId: 'poddr-5dee7',
    authDomain: 'poddr-5dee7.firebaseapp.com',
    storageBucket: 'poddr-5dee7.appspot.com',
    measurementId: 'G-S1QFLWRTV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGH5uuq41mL4B6BQeM41rnvIsBpVD055U',
    appId: '1:77230078110:android:c1e224133d4bd5476e238f',
    messagingSenderId: '77230078110',
    projectId: 'poddr-5dee7',
    storageBucket: 'poddr-5dee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAagn3bk3dYotwb8CP1T4R6H4Zl5RIrSfE',
    appId: '1:77230078110:ios:7723c2a4dbc9e7d16e238f',
    messagingSenderId: '77230078110',
    projectId: 'poddr-5dee7',
    storageBucket: 'poddr-5dee7.appspot.com',
    iosClientId: '77230078110-lo5pt4ls60utro9vp4uhnu1pdb1c1q38.apps.googleusercontent.com',
    iosBundleId: 'com.example.poddr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAagn3bk3dYotwb8CP1T4R6H4Zl5RIrSfE',
    appId: '1:77230078110:ios:7723c2a4dbc9e7d16e238f',
    messagingSenderId: '77230078110',
    projectId: 'poddr-5dee7',
    storageBucket: 'poddr-5dee7.appspot.com',
    iosClientId: '77230078110-lo5pt4ls60utro9vp4uhnu1pdb1c1q38.apps.googleusercontent.com',
    iosBundleId: 'com.example.poddr',
  );
}
